# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\x8c\x01\n\x0fTelemetrySample\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\traw_value\x18\x02 \x01(\x01\x12\x16\n\x0e\x66iltered_value\x18\x03 \x01(\x01\x12\x14\n\x0c\x61larm_active\x18\x04 \x01(\x08\x12\x11\n\tfsm_state\x18\x05 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"1\n\x0cTelemetryAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\"$\n\x11NodeStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"]\n\nNodeStatus\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tfsm_state\x18\x02 \x01(\t\x12\x17\n\x0fprocessed_count\x18\x03 \x01(\x04\x12\x12\n\nlast_value\x18\x04 \x01(\x01\x32\xa7\x01\n\x10TelemetryService\x12M\n\x0fStreamTelemetry\x12\x1c.telemetry.NodeStatusRequest\x1a\x1a.telemetry.TelemetrySample0\x01\x12\x44\n\rGetNodeStatus\x12\x1c.telemetry.NodeStatusRequest\x1a\x15.telemetry.NodeStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYSAMPLE']._serialized_start=31
  _globals['_TELEMETRYSAMPLE']._serialized_end=171
  _globals['_TELEMETRYACK']._serialized_start=173
  _globals['_TELEMETRYACK']._serialized_end=222
  _globals['_NODESTATUSREQUEST']._serialized_start=224
  _globals['_NODESTATUSREQUEST']._serialized_end=260
  _globals['_NODESTATUS']._serialized_start=262
  _globals['_NODESTATUS']._serialized_end=355
  _globals['_TELEMETRYSERVICE']._serialized_start=358
  _globals['_TELEMETRYSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
